# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Issues with these labels will never be considered stale
exemptLabels:
  - wip

# Label to use when marking an issue as stale
staleLabel: 'Status: Abandonado'

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Esta issue foi automaticamente marcada como obsoleta por não teve
  atividade nos últimos 30 dias. Ela será fechada caso nenhuma outra
  atividade ocorra. Obrigado por suas contribuições.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false