---
name: Nova micronação
about: Use este modelo para iniciar o processo de inclusão de sua micronação.
title: Adicionar micronação - (nome da micronação)
labels: nova-micronacao
assignees: joaosantana

---

Informe os seguintes dados:

- O nome comum da micronação;
- O nome oficial da micronação;
- Sua data de fundação;
- Sua forma de governo;
- Seus chefes de Estado e de Governo;
- Website;
- Redes sociais (Facebook, Twitter);
- Praça Pública (fórum, lista, etc.)